services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ttronics_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ttronics_db -h localhost -p 5432"]
      interval: 3s
      timeout: 5s
      retries: 10

  api:
    build: .
    restart: on-failure
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - .:/app:cached
    command: /bin/sh -c "\
      until pg_isready -h db -p 5432 -U postgres; do echo 'Waiting for postgres...'; sleep 1; done && \
      alembic upgrade head && \
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db_data:
  pgadmin_data:
